name: components-library
run-name: Deploy
on: [ push ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: cd ./packages/lib
      - run: pnpm ci
      - run: pnpm run build
      - run: cp ./package.json ./dist/package.json
      - run: cp ./package-lock.json ./dist/package-lock.json
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: cd dist && pnpm publish